# Generated by Django 4.1 on 2023-03-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_coustomer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('TW', 'Top Wear'), ('BW', 'Bottom Bear'), ('Vegetable', 'Vegetable oil'), ('Canola', 'Canola oil'), ('Sunflower', 'Sunflower oil'), ('Olive', 'Olive oil'), ('Peanut', 'Peanut oil'), ('Sesame', 'Sesame oil'), ('Coconut', 'Coconut oil'), ('Corn', 'Corn oil'), ('Soybean', 'Soybean oil'), ('Palm', 'Palm oil')], max_length=200),
        ),
    ]
